version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
